package i.a.a;

import kotlin.jvm.internal.m;
import kotlin.n;

/* compiled from: Parceler.kt */
/* loaded from: classes3.dex */
public interface a<T> {

    /* compiled from: Parceler.kt */
    /* renamed from: i.a.a.a$a  reason: collision with other inner class name */
    /* loaded from: classes3.dex */
    public static final class C0405a {
        public static <T> T[] a(a<T> aVar, int i2) {
            m.g(aVar, "this");
            throw new n("Generated by Android Extensions automatically");
        }
    }
}