package com.coinbase.wallet.consumer.di;

import com.coinbase.wallet.consumer.viewmodels.ConsumerAccountsViewModel;
import com.coinbase.wallet.consumer.viewmodels.ConsumerAccountsViewModel_AssistedFactory;
import com.coinbase.wallet.consumer.viewmodels.ConsumerAmountPickerViewModel;
import com.coinbase.wallet.consumer.viewmodels.ConsumerAmountPickerViewModel_AssistedFactory;
import com.coinbase.wallet.consumer.viewmodels.ConsumerCardCDVViewModel;
import com.coinbase.wallet.consumer.viewmodels.ConsumerCardCDVViewModel_AssistedFactory;
import com.coinbase.wallet.consumer.viewmodels.ConsumerInterstitialViewModel;
import com.coinbase.wallet.consumer.viewmodels.ConsumerInterstitialViewModel_AssistedFactory;
import com.coinbase.wallet.consumer.viewmodels.ConsumerOnboardingViewModel;
import com.coinbase.wallet.consumer.viewmodels.ConsumerOnboardingViewModel_AssistedFactory;
import com.coinbase.wallet.consumer.viewmodels.ConsumerSecure3DVerificationViewModel;
import com.coinbase.wallet.consumer.viewmodels.ConsumerSecure3DVerificationViewModel_AssistedFactory;
import com.coinbase.wallet.consumer.viewmodels.ConsumerTransferConfirmationViewModel;
import com.coinbase.wallet.consumer.viewmodels.ConsumerTransferConfirmationViewModel_AssistedFactory;
import com.coinbase.wallet.consumer.viewmodels.ConsumerTransferMethodsViewModel;
import com.coinbase.wallet.consumer.viewmodels.ConsumerTransferMethodsViewModel_AssistedFactory;

/* loaded from: classes.dex */
public abstract class AssistedInject_ConsumerViewModelModule {
    private AssistedInject_ConsumerViewModelModule() {
    }

    abstract ConsumerAccountsViewModel.Factory bind_com_coinbase_wallet_consumer_viewmodels_ConsumerAccountsViewModel(ConsumerAccountsViewModel_AssistedFactory consumerAccountsViewModel_AssistedFactory);

    abstract ConsumerAmountPickerViewModel.Factory bind_com_coinbase_wallet_consumer_viewmodels_ConsumerAmountPickerViewModel(ConsumerAmountPickerViewModel_AssistedFactory consumerAmountPickerViewModel_AssistedFactory);

    abstract ConsumerCardCDVViewModel.Factory bind_com_coinbase_wallet_consumer_viewmodels_ConsumerCardCDVViewModel(ConsumerCardCDVViewModel_AssistedFactory consumerCardCDVViewModel_AssistedFactory);

    abstract ConsumerInterstitialViewModel.Factory bind_com_coinbase_wallet_consumer_viewmodels_ConsumerInterstitialViewModel(ConsumerInterstitialViewModel_AssistedFactory consumerInterstitialViewModel_AssistedFactory);

    abstract ConsumerOnboardingViewModel.Factory bind_com_coinbase_wallet_consumer_viewmodels_ConsumerOnboardingViewModel(ConsumerOnboardingViewModel_AssistedFactory consumerOnboardingViewModel_AssistedFactory);

    abstract ConsumerSecure3DVerificationViewModel.Factory bind_com_coinbase_wallet_consumer_viewmodels_ConsumerSecure3DVerificationViewModel(ConsumerSecure3DVerificationViewModel_AssistedFactory consumerSecure3DVerificationViewModel_AssistedFactory);

    abstract ConsumerTransferConfirmationViewModel.Factory bind_com_coinbase_wallet_consumer_viewmodels_ConsumerTransferConfirmationViewModel(ConsumerTransferConfirmationViewModel_AssistedFactory consumerTransferConfirmationViewModel_AssistedFactory);

    abstract ConsumerTransferMethodsViewModel.Factory bind_com_coinbase_wallet_consumer_viewmodels_ConsumerTransferMethodsViewModel(ConsumerTransferMethodsViewModel_AssistedFactory consumerTransferMethodsViewModel_AssistedFactory);
}