package kotlin.reflect.jvm.internal.impl.util;

import java.util.Set;
import kotlin.a0.s0;
import kotlin.jvm.internal.m;
import kotlin.l0.k;
import kotlin.reflect.jvm.internal.impl.name.Name;

/* compiled from: OperatorNameConventions.kt */
/* loaded from: classes3.dex */
public final class OperatorNameConventions {
    public static final Name AND;
    public static final Set<Name> ASSIGNMENT_OPERATIONS;
    public static final Set<Name> BINARY_OPERATION_NAMES;
    public static final Name COMPARE_TO;
    public static final k COMPONENT_REGEX;
    public static final Name CONTAINS;
    public static final Name DEC;
    public static final Set<Name> DELEGATED_PROPERTY_OPERATORS;
    public static final Name DIV;
    public static final Name DIV_ASSIGN;
    public static final Name EQUALS;
    public static final Name GET;
    public static final Name GET_VALUE;
    public static final Name HAS_NEXT;
    public static final Name INC;
    public static final OperatorNameConventions INSTANCE = new OperatorNameConventions();
    public static final Name INVOKE;
    public static final Name ITERATOR;
    public static final Name MINUS;
    public static final Name MINUS_ASSIGN;
    public static final Name MOD;
    public static final Name MOD_ASSIGN;
    public static final Name NEXT;
    public static final Name NOT;
    public static final Name OR;
    public static final Name PLUS;
    public static final Name PLUS_ASSIGN;
    public static final Name PROVIDE_DELEGATE;
    public static final Name RANGE_TO;
    public static final Name REM;
    public static final Name REM_ASSIGN;
    public static final Name SET;
    public static final Name SET_VALUE;
    public static final Set<Name> SIMPLE_UNARY_OPERATION_NAMES;
    public static final Name TIMES;
    public static final Name TIMES_ASSIGN;
    public static final Name TO_STRING;
    public static final Name UNARY_MINUS;
    public static final Set<Name> UNARY_OPERATION_NAMES;
    public static final Name UNARY_PLUS;

    static {
        Set<Name> e2;
        Set<Name> e3;
        Set<Name> e4;
        Set<Name> e5;
        Set<Name> e6;
        Name identifier = Name.identifier("getValue");
        m.f(identifier, "identifier(\"getValue\")");
        GET_VALUE = identifier;
        Name identifier2 = Name.identifier("setValue");
        m.f(identifier2, "identifier(\"setValue\")");
        SET_VALUE = identifier2;
        Name identifier3 = Name.identifier("provideDelegate");
        m.f(identifier3, "identifier(\"provideDelegate\")");
        PROVIDE_DELEGATE = identifier3;
        Name identifier4 = Name.identifier("equals");
        m.f(identifier4, "identifier(\"equals\")");
        EQUALS = identifier4;
        Name identifier5 = Name.identifier("compareTo");
        m.f(identifier5, "identifier(\"compareTo\")");
        COMPARE_TO = identifier5;
        Name identifier6 = Name.identifier("contains");
        m.f(identifier6, "identifier(\"contains\")");
        CONTAINS = identifier6;
        Name identifier7 = Name.identifier("invoke");
        m.f(identifier7, "identifier(\"invoke\")");
        INVOKE = identifier7;
        Name identifier8 = Name.identifier("iterator");
        m.f(identifier8, "identifier(\"iterator\")");
        ITERATOR = identifier8;
        Name identifier9 = Name.identifier("get");
        m.f(identifier9, "identifier(\"get\")");
        GET = identifier9;
        Name identifier10 = Name.identifier("set");
        m.f(identifier10, "identifier(\"set\")");
        SET = identifier10;
        Name identifier11 = Name.identifier("next");
        m.f(identifier11, "identifier(\"next\")");
        NEXT = identifier11;
        Name identifier12 = Name.identifier("hasNext");
        m.f(identifier12, "identifier(\"hasNext\")");
        HAS_NEXT = identifier12;
        Name identifier13 = Name.identifier("toString");
        m.f(identifier13, "identifier(\"toString\")");
        TO_STRING = identifier13;
        COMPONENT_REGEX = new k("component\\d+");
        Name identifier14 = Name.identifier("and");
        m.f(identifier14, "identifier(\"and\")");
        AND = identifier14;
        Name identifier15 = Name.identifier("or");
        m.f(identifier15, "identifier(\"or\")");
        OR = identifier15;
        Name identifier16 = Name.identifier("inc");
        m.f(identifier16, "identifier(\"inc\")");
        INC = identifier16;
        Name identifier17 = Name.identifier("dec");
        m.f(identifier17, "identifier(\"dec\")");
        DEC = identifier17;
        Name identifier18 = Name.identifier("plus");
        m.f(identifier18, "identifier(\"plus\")");
        PLUS = identifier18;
        Name identifier19 = Name.identifier("minus");
        m.f(identifier19, "identifier(\"minus\")");
        MINUS = identifier19;
        Name identifier20 = Name.identifier("not");
        m.f(identifier20, "identifier(\"not\")");
        NOT = identifier20;
        Name identifier21 = Name.identifier("unaryMinus");
        m.f(identifier21, "identifier(\"unaryMinus\")");
        UNARY_MINUS = identifier21;
        Name identifier22 = Name.identifier("unaryPlus");
        m.f(identifier22, "identifier(\"unaryPlus\")");
        UNARY_PLUS = identifier22;
        Name identifier23 = Name.identifier("times");
        m.f(identifier23, "identifier(\"times\")");
        TIMES = identifier23;
        Name identifier24 = Name.identifier("div");
        m.f(identifier24, "identifier(\"div\")");
        DIV = identifier24;
        Name identifier25 = Name.identifier("mod");
        m.f(identifier25, "identifier(\"mod\")");
        MOD = identifier25;
        Name identifier26 = Name.identifier("rem");
        m.f(identifier26, "identifier(\"rem\")");
        REM = identifier26;
        Name identifier27 = Name.identifier("rangeTo");
        m.f(identifier27, "identifier(\"rangeTo\")");
        RANGE_TO = identifier27;
        Name identifier28 = Name.identifier("timesAssign");
        m.f(identifier28, "identifier(\"timesAssign\")");
        TIMES_ASSIGN = identifier28;
        Name identifier29 = Name.identifier("divAssign");
        m.f(identifier29, "identifier(\"divAssign\")");
        DIV_ASSIGN = identifier29;
        Name identifier30 = Name.identifier("modAssign");
        m.f(identifier30, "identifier(\"modAssign\")");
        MOD_ASSIGN = identifier30;
        Name identifier31 = Name.identifier("remAssign");
        m.f(identifier31, "identifier(\"remAssign\")");
        REM_ASSIGN = identifier31;
        Name identifier32 = Name.identifier("plusAssign");
        m.f(identifier32, "identifier(\"plusAssign\")");
        PLUS_ASSIGN = identifier32;
        Name identifier33 = Name.identifier("minusAssign");
        m.f(identifier33, "identifier(\"minusAssign\")");
        MINUS_ASSIGN = identifier33;
        e2 = s0.e(identifier16, identifier17, identifier22, identifier21, identifier20);
        UNARY_OPERATION_NAMES = e2;
        e3 = s0.e(identifier22, identifier21, identifier20);
        SIMPLE_UNARY_OPERATION_NAMES = e3;
        e4 = s0.e(identifier23, identifier18, identifier19, identifier24, identifier25, identifier26, identifier27);
        BINARY_OPERATION_NAMES = e4;
        e5 = s0.e(identifier28, identifier29, identifier30, identifier31, identifier32, identifier33);
        ASSIGNMENT_OPERATIONS = e5;
        e6 = s0.e(identifier, identifier2, identifier3);
        DELEGATED_PROPERTY_OPERATORS = e6;
    }

    private OperatorNameConventions() {
    }
}